### ISSUE TITLE
please submit a new release

### ISSUE THREAD

**Issue by ladyada** [stm32duino/VL53L4CD#4]
so folks get this fix
https://github.com/stm32duino/VL53L4CD/pull/3
right now they are getting the old version

**Comment by fpistm** [comment]
Hi @ladyada 

I guess @cparata do not release it yet because you don't answer to his comment:
https://github.com/stm32duino/VL53L4CD/pull/2#issuecomment-1039356129


Edit:
It seems there is a mistake in the last release:
https://github.com/stm32duino/VL53L4CD/releases/tag/1.0.1

the library .properties has not been updated in the tag but after.

**Comment by cparata** [comment]
Hi all,
now it should be ok.
Let me know if it works also on your side.
Best Regards,
Carlo

**Comment by ladyada** [comment]
ok i replied to the comment
